// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package wm;

public final class WumpusMonitor_Stub
    extends java.rmi.server.RemoteStub
    implements wm.WMInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_currentWorld_0;
    private static java.lang.reflect.Method $method_gameOver_1;
    private static java.lang.reflect.Method $method_grab_2;
    private static java.lang.reflect.Method $method_join_3;
    private static java.lang.reflect.Method $method_killed_4;
    private static java.lang.reflect.Method $method_leave_5;
    private static java.lang.reflect.Method $method_shoot_6;
    private static java.lang.reflect.Method $method_turnLeft_7;
    private static java.lang.reflect.Method $method_turnRight_8;
    private static java.lang.reflect.Method $method_walk_9;
    
    static {
	try {
	    $method_currentWorld_0 = wm.WMInterface.class.getMethod("currentWorld", new java.lang.Class[] {ws.WumpusWorld.class});
	    $method_gameOver_1 = wm.WMInterface.class.getMethod("gameOver", new java.lang.Class[] {});
	    $method_grab_2 = wm.WMInterface.class.getMethod("grab", new java.lang.Class[] {ws.Agent.class});
	    $method_join_3 = wm.WMInterface.class.getMethod("join", new java.lang.Class[] {ws.Agent.class});
	    $method_killed_4 = wm.WMInterface.class.getMethod("killed", new java.lang.Class[] {ws.Agent.class});
	    $method_leave_5 = wm.WMInterface.class.getMethod("leave", new java.lang.Class[] {ws.Agent.class});
	    $method_shoot_6 = wm.WMInterface.class.getMethod("shoot", new java.lang.Class[] {ws.Agent.class});
	    $method_turnLeft_7 = wm.WMInterface.class.getMethod("turnLeft", new java.lang.Class[] {ws.Agent.class});
	    $method_turnRight_8 = wm.WMInterface.class.getMethod("turnRight", new java.lang.Class[] {ws.Agent.class});
	    $method_walk_9 = wm.WMInterface.class.getMethod("walk", new java.lang.Class[] {ws.Agent.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public WumpusMonitor_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of currentWorld(WumpusWorld)
    public void currentWorld(ws.WumpusWorld $param_WumpusWorld_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_currentWorld_0, new java.lang.Object[] {$param_WumpusWorld_1}, -9149345874680416345L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of gameOver()
    public void gameOver()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_gameOver_1, null, 5736731529201808777L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of grab(Agent)
    public void grab(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_grab_2, new java.lang.Object[] {$param_Agent_1}, -8014957209125394315L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of join(Agent)
    public void join(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_join_3, new java.lang.Object[] {$param_Agent_1}, 1521140894510410881L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of killed(Agent)
    public void killed(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_killed_4, new java.lang.Object[] {$param_Agent_1}, 5649366933779381790L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of leave(Agent)
    public void leave(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_leave_5, new java.lang.Object[] {$param_Agent_1}, -3097638429081310540L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of shoot(Agent)
    public void shoot(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_shoot_6, new java.lang.Object[] {$param_Agent_1}, -2675756012212764232L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of turnLeft(Agent)
    public void turnLeft(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_turnLeft_7, new java.lang.Object[] {$param_Agent_1}, -75264505647420283L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of turnRight(Agent)
    public void turnRight(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_turnRight_8, new java.lang.Object[] {$param_Agent_1}, -5887424182645229933L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of walk(Agent)
    public void walk(ws.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_walk_9, new java.lang.Object[] {$param_Agent_1}, -5426102191795581649L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
